---
title: Hospitalizações por TM em Áreas Rurais e Urbanas de um Estado Brasileiro 
subtitle: Medical Research Council - UK, Grant no. MR T03355X/1 
author:
- Jacyra Paiva de Araujo^[ Colaboradora | Center of Data and Knowledge Integration for Health (CIDACS) | Salvador | Brasil ] 
date: 2022
institute: Center of Data and Knowledge Integration for Health (CIDACS)
titlegraphic: "./style/title.png"
csl: style/chicago-fullnote-bibliography.csl
suppress-bibliography: true
bibliography: /home/luis/Documents/multimorbidity-library.bib 
lang: en-AU
output: powerpoint_presentation
---


```{r setup, include=FALSE}
dep <- function(x) {
  if (!all(x %in% installed.packages())) {
    install.packages(x[x %in% installed.packages()[, "Package"] == F])
  }
  lapply(x, require, character.only = T)
}


dep(c(
  "qrencoder", "knitr"
))

knitr::opts_chunk$set(echo = FALSE)
setwd(here::here())
```

# Introduction

- Multimorbidity (MM) has been reported to worsen cognitive performance [@weiMultimorbidityCognitiveDecline2020]. Mental disorders is well known to worsen cognitive performance as well: anxiety [@evansSocialIsolationCognitive2019] , depression [@shimadaDepressiveSymptomsCognitive2014], and schizophrenia [@castro-de-araujoSubtypingSchizophreniaBased2020].


## Question
- Do MM individuals with symptoms of depression and anxiety show impairment in cognitive performance?

# Data

- Cambridge Center for Aging and Neuroscience (Cam-CAN) [@shaftoCambridgeCentreAgeing2014; @taylorCambridgeCentreAgeing2017].
- Demographic and cognitive information of participants.
- The sample size was 1534 individuals 

# Method

- Unsupervised clustering using  the KAMILA R package [@fossKamilaClusteringMixedType2018]
- Optimal number of clusters using the prediction strength algo  from [@tibshiraniClusterValidationPrediction2005]
- Found two optimal clusters, one of which presented with higher psychiatric symptomatology (HADS scores, see Table). We called this group PMM (Table).
- A logistic regression model was then performed ordinal logistic regression, where the MMSE would be included as outcome categorized in levels (0-10, severe; 11-20, moderate; 21-25, mild; 26-30, no cognitive impairment), see Figure.



# Conclusions

- Subjects with mental MM and psychiatric disorders had worse cognitive performance.
- Older subjects with a greater number of diseases had worse cognitive performance.
- Education was inversely associated with cognitive impairment measured with MMSE.
